function P1_IdentPFca(action )

global dlg2

if nargin<1,
    action='initialize';
end;

p1 = pendulum1;

if strcmp(action,'initialize')
 dlgname = ['Angle setting'];
 [flag,dlg2] = figflag(dlgname,0);   % bring to front if it's alive
 if ~flag                           % else, create it
    dlg2 = figure(...
	  'color',[.3 .3 .3],...
	  'colormap',[],...
	  'menubar','none',...
	  'resize','off',...
 	  'visible','off',...
	  'Units','Normalized',...
	  'Position',[.3 .41 .4 .18],...
	  'Name',dlgname, ...
	  'NumberTitle','off');
    dlg2=gcf;
    uicontrol(dlg2,'style','frame',...
	  'Units','Normalized',...
	  'position',[0 0 1 1])
    uicontrol(dlg2,...
	  'style','pushbutton',...
	  'String','Check Angle',...
	  'Units','Normalized',...
	  'position', [0.1 0.1 0.3 .24],...
	  'callback','P1_IdentPFca(''AngM'')');
    uicontrol(dlg2,...
	  'style','pushbutton',...
	  'tag','pbutton',...
	  'String','Close',...
	  'Units','Normalized',...
	  'position', [0.6 0.1 0.3 0.24],...
	  'callback','P1_IdentPFca(''PendPar'')');
    uicontrol(dlg2,'style','text',...
	  'string','Set angle as 2.78 < a <3.48 ',...
	  'horizontalalignment','center',...
	  'Units','Normalized',...
	  'position', [0.1 0.7 0.8 0.2]);
    uicontrol(dlg2,'style','text',...
	  'string',' Current Angle :',...
	  'horizontalalignment','right',...
	  'Units','Normalized',...
	  'position', [0.15 0.45 0.4 0.2]);
    uicontrol(dlg2,'style','text',...
	  'string','3.14',...
	  'tag','Angle',...
	  'horizontalalignment','left',...
	  'Units','Normalized',...
	  'position', [0.65 0.45 0.33 0.2]);
 i=pi;
 set(dlg2,'visible','on');
 end
elseif strcmp(action,'AngM')
  Pos=get(p1,'position');
  AngleL = Pos(4) + pi;

  Hwnd = findobj ('tag', 'Angle');
  set(Hwnd,'string',num2str(AngleL));
 
elseif strcmp(action,'PendPar')
   close(dlg2);
end
