function P1_IdentCM(action )

global dlg2

if nargin<1,
    action='initialize';
end;

p1 = pendulum1;

if strcmp(action,'initialize')
 dlgname = ['Control magnitude identification'];
 [flag,dlg2] = figflag(dlgname,0);   % bring to front if it's alive
 if ~flag                           % else, create it
    dlg2 = figure(...
	  'color',[.3 .3 .3],...
	  'colormap',[],...         
 	  'menubar','none',...
	  'resize','off',...
 	  'visible','off',...
	  'Units','Normalized',...
	  'Position',[.3 .41 .4 .18],...
	  'Name',dlgname, ...
	  'NumberTitle','off');
    dlg2=gcf;
    uicontrol(dlg2,'style','frame',...
	  'Units','Normalized',...
	  'position',[0 0 1 1])
    uicontrol(dlg2,...
	  'style','pushbutton',...
	  'String','Set',...
	  'Units','Normalized',...
	  'position', [0.1 0.1 0.3 .24],...
	  'callback','P1_IdentCM(''SetC'')');
    uicontrol(dlg2,...
	  'style','pushbutton',...
	  'tag','pbutton',...
	  'String','Close',...
	  'Units','Normalized',...
	  'position', [0.6 0.1 0.3 0.24],...
	  'callback','P1_IdentCM(''CloseCM'')');
    uicontrol(dlg2,'style','text',...
	  'string','Set control value [-1 1]:',...
	  'horizontalalignment','center',...
	  'Units','Normalized',...
	  'position', [0.1 0.7 0.8 0.2]);
    uicontrol(dlg2,'style','text',...
	  'string','negative (motion Left to Right), positive (motion Right to Left)',...
	  'horizontalalignment','center',...
	  'Units','Normalized',...
	  'position', [0.1 0.6 0.8 0.2]);
    uicontrol(dlg2,'style','text',...
	  'string',' PWM duty:',...
	  'horizontalalignment','right',...
	  'Units','Normalized',...
	  'position', [0.05 0.45 0.25 0.2]);
    uicontrol(dlg2,'style','edit',...
	  'string','0.00',...
	  'tag','Ctrl',...
	  'horizontalalignment','center',...
	  'Units','Normalized',...
	  'position', [0.35 0.52 0.33 0.16]);
 i=pi;
 set(dlg2,'visible','on');
 end
elseif strcmp(action,'SetC')

  Hwnd = findobj ('tag', 'Ctrl');
  vstr = get(Hwnd,'string');
  v = str2num(vstr);

  set(p1,'pwmprescaler',0);
  CONTROL_ID	= 2;
  PWM_VALUES	= [0 0 0];  
  PWM_VALUES(CONTROL_ID) = v;
  set(p1,'pwm',PWM_VALUES);

elseif strcmp(action,'CloseCM')
  PWM_VALUES	= [0 0 0];  
  set(p1,'pwm',PWM_VALUES);
  close(dlg2);
end
