function Hwnd = P1_InfoMsgBox(Title,Msg)

Hwnd= figure(...
	  'color',[.4 .4 .4],...
	  'colormap',[],...
	  'menubar','none',...
	  'resize','off',...
 	  'visible','on',...
	  'Units','Normalized',...
	  'Position',[.29 .45 .5 .06],...
	  'Name',Title, ...
	  'NumberTitle','off');

  uicontrol(Hwnd,'style','text',...
	  'backgroundcolor',[.4 .4 .4],...
	  'string',Msg,...
	  'horizontalalignment','center',...
	  'Units','Normalized',...
	  'position', [0 0 1 0.7]);
