function P1_Test(action )

global dlg2

if nargin<1,
    action='initialize';
   p1 = pendulum1;
   PWM_VALUES	= [0 0 0];  
   set(p1,'pwm',PWM_VALUES);
   set(p1,'resetencoder',[0 0 0 1 1]);
end;

p1 = pendulum1;

if strcmp(action,'initialize')
 dlgname = ['Pendulum test'];
 [flag,dlg2] = figflag(dlgname,0);   % bring to front if it's alive
 if ~flag                           % else, create it
    dlg2 = figure(...
	  'color',[.3 .3 .3],...
	  'colormap',[],...
	  'menubar','none',...
	  'resize','off',...
 	  'visible','off',...
	  'Units','Normalized',...
	  'Position',[.3 .41 .4 .18],...
	  'Name',dlgname, ...
	  'NumberTitle','off');
    dlg2=gcf;
    uicontrol(dlg2,'style','frame',...
	  'Units','Normalized',...
	  'position',[0 0 1 1])
    uicontrol(dlg2,...
	  'style','pushbutton',...
	  'String','Get Positions',...
	  'Units','Normalized',...
	  'position', [0.1 0.1 0.3 .24],...
	  'callback','P1_Test(''GetMeas'')');
    uicontrol(dlg2,...
	  'style','pushbutton',...
	  'tag','pbutton',...
	  'String','Close',...
	  'Units','Normalized',...
	  'position', [0.6 0.1 0.3 0.24],...
	  'callback','P1_Test(''CloseTest'')');
    uicontrol(dlg2,'style','text',...
	  'string','Move the cart and pendulum, click Get Positions for current values',...
	  'horizontalalignment','center',...
	  'Units','Normalized',...
	  'position', [0.1 0.7 0.8 0.2]);
    uicontrol(dlg2,'style','text',...
	  'string',' Cart position:',...
	  'horizontalalignment','right',...
	  'Units','Normalized',...
	  'position', [0.05 0.5 0.25 0.2]);
    uicontrol(dlg2,'style','text',...
	  'string','0.00',...
	  'tag','CartPos',...
	  'horizontalalignment','center',...
	  'Units','Normalized',...
	  'position', [0.35 0.57 0.33 0.16]);
    uicontrol(dlg2,'style','text',...
	  'string',' Pendulum angle:',...
	  'horizontalalignment','right',...
	  'Units','Normalized',...
	  'position', [0.05 0.35 0.25 0.2]);
    uicontrol(dlg2,'style','text',...
	  'string','0.00',...
	  'tag','PendPos',...
	  'horizontalalignment','center',...
	  'Units','Normalized',...
	  'position', [0.35 0.42 0.33 0.16]);
 i=pi;
 set(dlg2,'visible','on');
 end
elseif strcmp(action,'GetMeas');

  PEND_POS_ID	= 4;
  CART_POS_ID	= 5;

  Pos = get(p1,'position');
  CartPos = Pos(CART_POS_ID);
  PendPos = Pos(PEND_POS_ID);

  Hwnd = findobj ('tag', 'CartPos');
  set(Hwnd,'string',num2str(CartPos));
  Hwnd = findobj ('tag', 'PendPos');
  set(Hwnd,'string',num2str(PendPos));


elseif strcmp(action,'CloseTest')
  close(dlg2);
end
